CREATE TABLE IF NOT EXISTS "user" (
    email VARCHAR(255) PRIMARY KEY,
    passwordHash VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_verified BOOLEAN DEFAULT FALSE,
    otp VARCHAR(6) DEFAULT NULL
);